services:
  - type: web
    name: Freelancermrsingh
    env: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn portfolio_freelance.wsgi:application"
    # Explicitly set the Python version
    pythonVersion: "3.9.16"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_freelance.settings_prod
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: GEMINI_API_KEY
        sync: false