services:
  - type: web
    name: Freelancermrsingh
    env: python
    buildCommand: "chmod +x build.sh && PYTHON_VERSION=3.9 ./build.sh"
    startCommand: "PYTHON_VERSION=3.9 gunicorn portfolio_freelance.wsgi:application"
    pythonVersion: "3.9.16"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_freelance.settings_prod
      - key: DB_NAME
        value: portfolio_db
      - key: DB_USER
        value: postgres
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: 5432
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: GEMINI_API_KEY
        sync: false